[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing (important for React router if you add it later)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add cache control headers for API responses
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"